apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
   DB_PASSWORD: cGFzc0B3b3Jk
   DB_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
   DB_USER: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
    name: smtp-secret
type: Opaque
data:
  SMTP_TOKEN: eGVueGd5cWxkaHltcGV6bw==
  EMAIL_ID: bm9yZXBseUBjbG9ja2hhc2guY29t
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi0yMjU5MjEwIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiZkRvNEpTeWhYYkRNYTZNaHNhUmIiLAogICAgICAgICAgICAiYXV0aCI6IloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMHlNalU1TWpFd09tWkVielJLVTNsb1dHSkVUV0UyVFdoellWSmkiCiAgICAgICAgfQogICAgfQp9Cg==
